---
- name: "MOTD Copy"
  hosts: all
  gather_facts: yes
  tasks:

  - name: Copy a new motd file into place and back up the original if it differs
    copy:
      src: /root/testmotd
      dest: /root/testmotd.tst
      owner: root
      group: root
      mode: '0644'
      backup: yes
