---
- name: "MOTD Copy"
  hosts: all
  become: yes
  gather_facts: yes
  tasks:

  - name: Copy a new motd file into place and back up the original if it differs
    copy:
      remote_src: yes
      src: /tmp/testmotd
      dest: /tmp/testmotd
