--- 
- name: "Create users on AIX"
  hosts: Power_VIO
  collections:
  - ibm.power_aix
  tasks:
  
  - name: Create joker user
    user:
      state: present
      name: joker
      attributes:
        id: 1182
        groups: joker,ldap
        pgrp: joker
